### ISSUE TITLE
wiki: uncheck "Restrict editing to collaborators only"

### ISSUE THREAD

**Issue by tjyang** [google-apis-rs/apis#3]
* As non-collaborator, I can't add wiki page with following button checked.

![image](https://user-images.githubusercontent.com/378638/63223079-e0e5c600-c175-11e9-8c7c-86c99da2329c.png)

* Please feel free to put back the restriction if it is abused with non project related notes from others.

**Comment by Byron** [comment]
@tjyang Sorry for the hassle. Please try again, it should work now :).
